### PR TITLE
Fix setting Reply-To multiple times

### LINKED ISSUE #299: Can not override h:reply-to using setReplyToAddress
Because it throws an exception "array_push() expects parameter 1 to be array, string given" on 114 line in Mailgun\Messages\MessageBuilder.

### PR DESCRIPTION
**Pull request by z38**
Fixes #299

### CODE REVIEW

File: src/Mailgun/Messages/MessageBuilder.php [hunk 1]
```diff
@@ -117,10 +117,10 @@ protected function addRecipient($headerName, $address, $variables)
     {
         $compiledAddress = $this->parseAddress($address, $variables);
 
-        if (isset($this->message[$headerName])) {
-            array_push($this->message[$headerName], $compiledAddress);
-        } elseif ($headerName == 'h:reply-to') {
+        if ($headerName == 'h:reply-to') {
```
Comment (DavidGarciaCat) [inline src/Mailgun/Messages/MessageBuilder.php]: I would say to compare strictly `===`

Comment (z38) [inline src/Mailgun/Messages/MessageBuilder.php]: :+1: Done
